### ISSUE TITLE
When debug in eclipse the ofmeet exception ,Which version of jitsi-android-osgi-1.0-SNAPSHOT.jar?

### ISSUE THREAD

**Issue by cnscns** [igniterealtime/Openfire-Meetings#71]
14:10:56,769 ERROR PluginManager:472 - An exception occurred while loading plugin 'ofmeet':
java.lang.NoSuchMethodError: org.jitsi.impl.osgi.framework.OSGiLauncher.<init>([[Ljava/lang/String;)V
	at org.jitsi.meet.OSGi.start(OSGi.java:58)
	at org.jitsi.videobridge.xmpp.ComponentImpl.postComponentStart(ComponentImpl.java:578)
	at org.xmpp.component.AbstractComponent.start(AbstractComponent.java:967)
	at org.jivesoftware.openfire.component.InternalComponentManager.addComponent(InternalComponentManager.java:159)
	at org.jitsi.videobridge.openfire.PluginImpl.initializePlugin(PluginImpl.java:187)
	at org.jivesoftware.openfire.plugin.ofmeet.JitsiPluginWrapper.initialize(JitsiPluginWrapper.java:47)
	at org.jivesoftware.openfire.plugin.ofmeet.OfMeetPlugin.initializePlugin(OfMeetPlugin.java:121)
	at org.jivesoftware.openfire.container.PluginManager.loadPlugin(PluginManager.java:410)
	at org.jivesoftware.openfire.container.PluginMonitor$MonitorTask$4.call(PluginMonitor.java:276)
	at org.jivesoftware.openfire.container.PluginMonitor$MonitorTask$4.call(PluginMonitor.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by cnscns** [comment]
I use Openfire-Meetings-0.9.3

**Comment by cnscns** [comment]
Sorry! The org.jitsi.meet.OSGi is in jicoco-1.1-SNAPSHOT.jar I think the  jicoco-1.1-SNAPSHOT.jar is wrong

**Comment by guusdk** [comment]
I'm afraid that we're unlikely to be able to spend time on supporting Eclipse-specific problems. Also, I'd appreciate it if you'd not create support questions in this issue tracker. We have an excellent forum for that at https://discourse.igniterealtime.org
