### ISSUE TITLE
Using the https://codeload.github.com/jitsi/jicoco/tar.gz/43 report bellow erros

### ISSUE THREAD

**Issue by cnscns** [igniterealtime/Openfire-Meetings#72]
org.xmpp.component.ComponentException: java.lang.IllegalStateException: Class Loader not initialized
	at org.jivesoftware.openfire.component.InternalComponentManager.addComponent(InternalComponentManager.java:183)
	at org.jitsi.videobridge.openfire.PluginImpl.initializePlugin(PluginImpl.java:187)
	at org.jivesoftware.openfire.plugin.ofmeet.JitsiPluginWrapper.initialize(JitsiPluginWrapper.java:47)
	at org.jivesoftware.openfire.plugin.ofmeet.OfMeetPlugin.initializePlugin(OfMeetPlugin.java:121)
	at org.jivesoftware.openfire.container.PluginManager.loadPlugin(PluginManager.java:410)
	at org.jivesoftware.openfire.container.PluginMonitor$MonitorTask$4.call(PluginMonitor.java:276)
	at org.jivesoftware.openfire.container.PluginMonitor$MonitorTask$4.call(PluginMonitor.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Class Loader not initialized
	at org.jitsi.meet.OSGi.start(OSGi.java:60)
	at org.jitsi.videobridge.xmpp.ComponentImpl.postComponentStart(ComponentImpl.java:578)
	at org.xmpp.component.AbstractComponent.start(AbstractComponent.java:967)
	at org.jivesoftware.openfire.component.InternalComponentManager.addComponent(InternalComponentManager.java:159)

**Comment by guusdk** [comment]
I am unsure what codeload is, or why you would use it. If it results in problems, I'm unwilling to help out. Please report back if you have issues with running the artifacts that we provide in this repository. Any third party modifications, we're unlikely to support without very good cause (our resources are limited, I'm afraid).
