### ISSUE TITLE
FocusPlugin exception

### ISSUE THREAD

**Issue by cnscns** [igniterealtime/Openfire-Meetings#73]
2018.06.12 17:30:18 org.jivesoftware.openfire.plugin.ofmeet.FocusPlugin - An exception occurred while initializing the Jitsi Jicofo wrapper.
java.lang.IllegalStateException: Class Loader not initialized
        at org.jitsi.meet.OSGi.start(OSGi.java:60)
        at org.jitsi.jicofo.xmpp.FocusComponent.init(FocusComponent.java:128)
        at org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper.initialize(JitsiJicofoWrapper.java:101)
        at org.jivesoftware.openfire.plugin.ofmeet.FocusPlugin$1.run(FocusPlugin.java:71)
2018.06.12 17:30:21 org.jivesoftware.openfire.plugin.ofmeet.FocusPlugin - An exception occurred while initializing the Jitsi Jicofo wrapper.
java.lang.IllegalStateException: Class Loader not initialized
        at org.jitsi.meet.OSGi.start(OSGi.java:60)
        at org.jitsi.jicofo.xmpp.FocusComponent.init(FocusComponent.java:128)
        at org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper.initialize(JitsiJicofoWrapper.java:101)
        at org.jivesoftware.openfire.plugin.ofmeet.FocusPlugin$1.run(FocusPlugin.java:71)
2018.06.12 17:30:23 org.jivesoftware.openfire.plugin.ofmeet.FocusPlugin - An exception occurred while initializing the Jitsi Jicofo wrapper.
java.lang.IllegalStateException: Class Loader not initialized
        at org.jitsi.meet.OSGi.start(OSGi.java:60)
        at org.jitsi.jicofo.xmpp.FocusComponent.init(FocusComponent.java:128)
        at org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper.initialize(JitsiJicofoWrapper.java:101)
        at org.jivesoftware.openfire.plugin.ofmeet.FocusPlugin$1.run(FocusPlugin.java:71)
2018.06.12 17:30:26 org.jivesoftware.openfire.plugin.ofmeet.FocusPlugin - An exception occurred while initializing the Jitsi Jicofo wrapper.
java.lang.IllegalStateException: Class Loader not initialized
        at org.jitsi.meet.OSGi.start(OSGi.java:60)
        at org.jitsi.jicofo.xmpp.FocusComponent.init(FocusComponent.java:128)
        at org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper.initialize(JitsiJicofoWrapper.java:101)
        at org.jivesoftware.openfire.plugin.ofmeet.FocusPlugin$1.run(FocusPlugin.java:71)
2018.06.12 17:30:28 org.jivesoftware.openfire.plugin.ofmeet.FocusPlugin - An exception occurred while initializing the Jitsi Jicofo wrapper.
java.lang.IllegalStateException: Class Loader not initialized
        at org.jitsi.meet.OSGi.start(OSGi.java:60)
        at org.jitsi.jicofo.xmpp.FocusComponent.init(FocusComponent.java:128)
        at org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper.initialize(JitsiJicofoWrapper.java:101)
        at org.jivesoftware.openfire.plugin.ofmeet.FocusPlugin$1.run(FocusPlugin.java:71)
2018.06.12 17:30:31 org.jivesoftware.openfire.plugin.ofmeet.FocusPlugin - An exception occurred while initializing the Jitsi Jicofo wrapper.
java.lang.IllegalStateException: Class Loader not initialized

**Comment by cnscns** [comment]
When I build Openfire-Meetings-0.9.3.tar.gz  and openfire_src_4_2_3.tar.gz on Linux,Load plugins from admin client and then create meetings(https://x.x.x.x:7443/ofmeet),the error log above

**Comment by deleolajide** [comment]
I have been getting the same error. I have reverted back to 0.9.2 for now and waiting for 0.9.4

**Comment by guusdk** [comment]
I'm not getting thesed in 0.9.4, which was released recently. Please re-open if the problem persists!

**Comment by cnscns** [comment]
Down load source code then compile ,After adding Openfire-Meetings
 plugin to openfire from the admin client,then kickoff meet ,crash as above
