### ISSUE TITLE
complie 0.9.4 and run ,exception as below

### ISSUE THREAD

**Issue by cnscns** [igniterealtime/Openfire-Meetings#76]
java.lang.IncompatibleClassChangeError: class net.java.sip.communicator.impl.protocol.jabber.extensions.colibri.ColibriIQProvider has interface org.jivesoftware.smack.provider.IQProvider as super class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jitsi.videobridge.Videobridge.start(Videobridge.java:1430)
	at org.jitsi.videobridge.VideobridgeBundleActivator.start(VideobridgeBundleActivator.java:55)
	at org.jitsi.impl.osgi.framework.BundleImpl.start(BundleImpl.java:307)
	at org.jitsi.impl.osgi.framework.launch.FrameworkImpl.startLevelChanged(FrameworkImpl.java:472)
	at org.jitsi.impl.osgi.framework.startlevel.FrameworkStartLevelImpl$Command.run(FrameworkStartLevelImpl.java:137)
	at org.jitsi.impl.osgi.framework.AsyncExecutor.runInThread(AsyncExecutor.java:122)
	at org.jitsi.impl.osgi.framework.AsyncExecutor.access$000(AsyncExecutor.java:28)
	at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:231)
11:07:48,576 ERROR FrameworkImpl:480 - Error changing start level
org.osgi.framework.BundleException: BundleActivator.start
	at org.jitsi.impl.osgi.framework.BundleImpl.start(BundleImpl.java:327)
	at org.jitsi.impl.osgi.framework.launch.FrameworkImpl.startLevelChanged(FrameworkImpl.java:472)
	at org.jitsi.impl.osgi.framework.startlevel.FrameworkStartLevelImpl$Command.run(FrameworkStartLevelImpl.java:137)
	at org.jitsi.impl.osgi.framework.AsyncExecutor.runInThread(AsyncExecutor.java:122)
	at org.jitsi.impl.osgi.framework.AsyncExecutor.access$000(AsyncExecutor.java:28)
	at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:231)
Caused by: java.lang.IncompatibleClassChangeError: class net.java.sip.communicator.impl.protocol.jabber.extensions.colibri.ColibriIQProvider has interface org.jivesoftware.smack.provider.IQProvider as super class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jitsi.videobridge.Videobridge.start(Videobridge.java:1430)
	at org.jitsi.videobridge.VideobridgeBundleActivator.start(VideobridgeBundleActivator.java:55)
	at org.jitsi.impl.osgi.framework.BundleImpl.start(BundleImpl.java:307)
	... 5 more

**Comment by cnscns** [comment]
I think  the jar version is not compatible

**Comment by guusdk** [comment]
Do you have the same runtime issues when you use the artifacts that we [provide here](https://github.com/igniterealtime/Openfire-Meetings/releases/tag/v0.9.4), instead of building your own version?

**Comment by cnscns** [comment]
using openfire 4.1.5 or 4.2.3 and using the jar file from provide link ,the same error
